name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: spmproject/spm-front-end
        registry: docker.io
        username: spmproject
        password: spmproject_123
        
